name: flutter_change_theme
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  rx_shared_preference: ^1.0.0+2
  distinct_value_connectable_observable: ^2.0.0+2
  flutter_bloc_pattern: ^0.0.1+1
  flutter_provider: ^1.1.0+3
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
